name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Send deploy trigger
      env:
        deploy_url: ${{ secrets.DeployUrl }}
      run: curl -q $deploy_url